# Generated by Django 6.0.1 on 2026-01-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='id_kategori',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produk',
            name='harga',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='status',
            name='id_status',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
